//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CornerstoneFVModel.rc
//
#define ID_BUTTON_RESET                 3
#define ID_ADD                          3
#define ID_BUTTON_SAVE                  3
#define ID_BUTTON_EXPORT_RANKINGS       4
#define ID_EDIT                         4
#define ID_BUTTON_DELETE                4
#define ID_DELETE                       5
#define ID_BUTTON_NEW                   5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CORNERSTONEFVMODEL_FORM     101
#define IDD_DIALOG_STOCK_APLHABETICAL   103
#define IDR_MAINFRAME                   128
#define IDR_MODELTYPE                   129
#define IDR_GENERAL                     129
#define IDB_CLOSE                       130
#define IDB_CLOSE_ON                    131
#define IDB_CLOSE_PRESS                 132
#define IDB_SPLASH                      133
#define IDB_CORNERSTONE                 134
#define IDB_STOCK_1                     135
#define IDC_CURSOR_FIXEDCOL             136
#define IDC_CURSOR_FIXEDROW             137
#define IDC_CURSOR_RESIZE_COL           138
#define IDC_CURSOR_RESIZE_ROW           139
#define IDI_FOLDER                      140
#define IDI_STOCK                       141
#define IDI_SECTOR                      142
#define IDI_RANK                        143
#define IDD_DIALOG_LOGIN                144
#define IDD_DIALOG_SENS_ANALYSIS        145
#define IDD_FORM_MONTECARLO             146
#define IDD_DIALOG_MONTECARLO_INPUTS    147
#define IDB_BITMAP_DISTRIB              147
#define IDI_ICON_GREEN                  149
#define IDI_ICON_RED                    150
#define IDI_ICON_YELLOW                 151
#define IDI_ICON_BLUE                   152
#define IDD_DIALOG_LAST_REPORT_YEAR     154
#define IDD_DIALOG_MACRO                155
#define IDD_DIALOG_UPLOAD_DATA          156
#define IDD_DIALOG_HISTORY              157
#define IDR_HISTORY                     157
#define IDD_DIALOG_DATE                 158
#define IDD_DIALOG_CHARTS               159
#define IDB_STOCK                       159
#define IDD_DIALOG_SECTORS              160
#define IDD_DIALOG_NAME                 161
#define IDD_DIALOG_COMPANIES            162
#define IDD_DIALOG_NAME_AND_TICKER      164
#define IDD_DIALOGBAR_GOTOTICKER        165
#define IDI_INDEX                       165
#define IDD_DIALOG_MEETINGS             166
#define IDB_BITMAP_MEETING              166
#define IDR_MEETINGS                    167
#define IDD_DIALOG_ADD_MEETING          168
#define IDB_BITMAP_DOC                  171
#define IDD_DIALOG_FILTER_MEETINGS      172
#define IDR_CHARTS                      174
#define IDD_DIALOG_EPS_GRAPH            175
#define IDD_DIALOG_SPLIT                176
#define IDD_DIALOG_DATA_CHECK           177
#define IDD_DIALOG_TABLE                178
#define IDR_CHANGES                     179
#define IDD_DIALOG_HTML                 179
#define IDR_TABLE                       180
#define IDI_TYPE                        181
#define IDD_DIALOG_REP_EBITDA_LEV       182
#define IDD_DIALOG_MAP                  183
#define IDR_MAP                         184
#define IDD_DIALOG_CHANGES              185
#define IDD_DIALOG_MAP_STEP             187
#define IDR_HTML                        188
#define IDD_DIALOG_REP_EARNINGS_MOMENTUM 189
#define IDD_DIALOG_REP_VALUE_MOMENTUM_1 190
#define IDD_DIALOG_REP_GENERAL          191
#define IDD_DIALOG_CONNECTION           192
#define IDD_DIALOG_MAP_SECTORS          193
#define IDD_DIALOG_SELECT_UNIVERSE      194
#define IDD_DIALOG_DAILYSUMMARY         195
#define IDB_BITMAP_GOODBAD_1            196
#define IDD_DIALOG_2MINUTE              196
#define IDR_DAILYSUMMARIES              197
#define IDD_DIALOG_PREDICTABILITY       197
#define IDB_BITMAP_CIP2                 198
#define IDR_HTML_HW                     203
#define IDD_DIALOG_CHANGE_PASSWORD      205
#define IDD_DIALOG_CONFIRM_WEIGHT       206
#define IDD_DIALOG_2MINUTE_V2           208
#define IDD_DIALOG_INVPROCESS           209
#define IDD_DIALOG_SELECT_COMP          210
#define IDC_LIST_STOCKS                 1001
#define IDC_STATIC_CORNER               1002
#define IDC_STATIC_CAPTION              1003
#define IDC_EDIT_TICKER                 1004
#define IDC_BUTTON_OPEN                 1005
#define IDC_EDIT_CIQTICKER              1005
#define IDC_STATIC_TICKBORDER           1006
#define IDC_EDIT_LAST_REPORT_YEAR       1006
#define IDC_CHECK_USE_DEBT_ADJUST       1008
#define IDC_TAB_LISTS                   1009
#define IDC_STATIC_FRM2                 1009
#define IDC_TREE_INDUSTRIES             1010
#define IDC_CHECK_DOWNLOAD_BS           1010
#define IDC_TREE_SECTORS                1011
#define IDC_CHECK_DOWNLOAD_EPS          1011
#define IDC_TREE_RANKS                  1012
#define IDC_STATIC_DATE                 1012
#define IDC_TREE_INDEXES                1013
#define IDC_CHECK_DOWNLOAD_ROCROE       1013
#define IDC_EDIT_NAME                   1014
#define IDC_TREE_TYPES                  1014
#define IDC_EDIT_PASSWORD               1015
#define IDC_STATIC_MULTIPLE             1017
#define IDC_STATIC_ROI                  1018
#define IDC_COMBO_VIEW                  1019
#define IDC_LIST                        1020
#define IDC_EDIT_ROC                    1021
#define IDC_COMBO_DISTRIB               1021
#define IDC_SLIDER_ROC                  1022
#define IDC_EDIT_F1                     1022
#define IDC_EDIT_ROE                    1023
#define IDC_EDIT_F2                     1023
#define IDC_SLIDER_ROE                  1024
#define IDC_RADIO_DIRECTION_1           1024
#define IDC_EDIT_EPS                    1025
#define IDC_RADIO_DIRECTION_2           1025
#define IDC_SLIDER_EPS                  1026
#define IDC_RADIO_DIRECTION_3           1026
#define IDC_EDIT_DISCOUNT               1027
#define IDC_RADIO_VARIANCE_1            1027
#define IDC_SLIDER_DISCOUNT             1028
#define IDC_RADIO_VARIANCE_2            1028
#define IDC_EDIT_EPS_NEXT               1029
#define IDC_RADIO_VARIANCE_3            1029
#define IDC_SLIDER_EPS_NEXT             1030
#define IDC_BUTTON_SETPARAMS            1030
#define IDC_EDIT_DIV                    1031
#define IDC_BUTTON_RUN                  1031
#define IDC_SLIDER_DIV                  1032
#define IDC_EDIT_ITERATIONS             1032
#define IDC_EDIT_DEBT                   1033
#define IDC_CHECK_INTERACTIVE           1033
#define IDC_SLIDER_DEBT                 1034
#define IDC_CHECK_OUT_ACTUAL            1034
#define IDC_EDIT_PRICE                  1035
#define IDC_CHECK_OUT_FORE              1035
#define IDC_TAB_OUTS                    1035
#define IDC_SLIDER_PRICE                1036
#define IDC_CHECK_OUT_RAZOR             1036
#define IDC_CHECK_OUT_FORWARD_RAZOR     1037
#define IDC_SLIDER_LEFT                 1037
#define IDC_EDIT_PERCENT                1038
#define IDC_STATIC_MULTIPLE_FORE        1039
#define IDC_STATIC_PERCENT              1039
#define IDC_STATIC_ROI_FORE             1040
#define IDC_COMBO_TYPE                  1040
#define IDC_STATIC_MULTIPLE_RAZOR       1041
#define IDC_RADIO_OPTION_1              1041
#define IDC_STATIC_ROI_RAZOR            1042
#define IDC_RADIO_OPTION_2              1042
#define IDC_STATIC_MULTIPLE_RAZOR_FORE  1043
#define IDC_EDIT_YEAR                   1043
#define IDC_STATIC_ROI_RAZOR_FORE       1044
#define IDC_EDIT_MAX_REINVEST           1044
#define IDC_EDIT_EPS_THIS               1045
#define IDC_EDIT_TAX                    1045
#define IDC_EDIT_BS_FILE                1045
#define IDC_SLIDER_EPS_THIS             1046
#define IDC_EDIT_INTEREST               1046
#define IDC_BUTTON_BS_BROWSE            1046
#define IDC_EDIT_EPS_LAST               1047
#define IDC_EDIT_INTERESTFACTOR         1047
#define IDC_EDIT_PR_FILE                1047
#define IDC_SLIDER_EPS_LAST             1048
#define IDC_BUTTON_PR_BROWSE            1048
#define IDC_STATIC_GROWTH               1049
#define IDC_EDIT_YEARS_DISCOUNT_EARNINGS 1049
#define IDC_CHECK_FORCE_BS              1049
#define IDC_STATIC_GROWTH_FORE          1050
#define IDC_EDIT_YEARS_EPSROI_MEANS     1050
#define IDC_EDIT_EPS_FILE               1050
#define IDC_STATIC_GROWTH_RAZOR         1051
#define IDC_EDIT_PERIODS_MOVING_AVE     1051
#define IDC_BUTTON_EPS_BROWSE           1051
#define IDC_STATIC_GROWTH_RAZOR_FORE    1052
#define IDC_CHECK_FORCE_EPS             1052
#define IDC_EDIT_MIN_GROWTH             1052
#define IDC_EDIT_RET_FILE               1053
#define IDC_BUTTON_RET_BROWSE           1054
#define IDC_EDIT_SHARES_FILE            1055
#define IDC_BUTTON_SHARES_BROWSE        1056
#define IDC_STATIC_NAME                 1057
#define IDC_EDIT_M                      1062
#define IDC_EDIT_D                      1063
#define IDC_EDIT_SYMBOLS                1063
#define IDC_EDIT_Y                      1064
#define IDC_LIST_MAIN                   1064
#define IDC_COMBO_INDUSTRY              1069
#define IDC_COMBO_SECTOR                1070
#define IDC_CHECK_LOAD_BS               1072
#define IDC_CHECK_LOAD_EPS              1073
#define IDC_EDIT_W1                     1074
#define IDC_EDIT_W2                     1075
#define IDC_EDIT_BASE                   1075
#define IDC_EDIT_W3                     1076
#define IDC_STATIC_TOKENS               1076
#define IDC_EDIT_W4                     1077
#define IDC_STATIC_BASE                 1077
#define IDC_EDIT_W5                     1078
#define IDC_EDIT_W6                     1079
#define IDC_COMBO_COMPANY               1079
#define IDC_EDIT_W7                     1080
#define IDC_EDIT_DATE                   1080
#define IDC_COMBO_ANALYST               1080
#define IDC_EDIT_W8                     1081
#define IDC_EDIT_ANALYST                1081
#define IDC_EDIT_ITEMDATE               1081
#define IDC_EDIT_W9                     1082
#define IDC_COMBO_REC                   1082
#define IDC_COMBO_VISION                1082
#define IDC_COMBO_DEC                   1083
#define IDC_CHECK_LOAD_ROCROE           1083
#define IDC_COMBO_EXECUTION             1083
#define IDC_LIST_FILES                  1084
#define IDC_COMBO_TARGET_WEIGHT         1084
#define IDC_EDIT_DESC                   1085
#define IDC_COMBO_BIAS                  1085
#define IDC_BUTTON_OPEN_FILE            1086
#define IDC_BUTTON_ADD_FILE             1087
#define IDC_CHECK_FROM                  1087
#define IDC_BUTTON_DELETE_FILE          1088
#define IDC_EDIT_FROM_M                 1088
#define IDC_BUTTON_DELETE_ALLFILES      1089
#define IDC_EDIT_FROM_D                 1089
#define IDC_EDIT_FROM_Y                 1090
#define IDC_EDIT_TO_M                   1091
#define IDC_EDIT_TO_D                   1092
#define IDC_EDIT_TO_Y                   1093
#define IDC_CHECK_TO                    1094
#define IDC_RADIO_SORT                  1095
#define IDC_RADIO_SORT2                 1096
#define IDC_TAB                         1096
#define IDC_STATIC_FOOTER               1097
#define IDC_EDIT_NAME_LOOKUP            1098
#define IDC_EDIT_AFTER                  1099
#define IDC_EDIT_BEFORE                 1100
#define IDC_EDIT_NORMALIZED             1101
#define IDC_RADIO_NORMALIZED_1          1102
#define IDC_EDIT_PERIODS                1103
#define IDC_RADIO_NORMALIZED_2          1104
#define IDC_RADIO_SORT_1                1104
#define IDC_RADIO_RAZOR_1               1105
#define IDC_RADIO2                      1105
#define IDC_RADIO_RAZOR_2               1106
#define IDC_RADIO3                      1106
#define IDC_EDIT_RAZOR                  1107
#define IDC_RADIO4                      1107
#define IDC_RADIO_BEV_1                 1108
#define IDC_RADIO5                      1108
#define IDC_RADIO_BEV_2                 1109
#define IDC_RADIO6                      1109
#define IDC_EDIT_BEV                    1110
#define IDC_RADIO7                      1110
#define IDC_RADIO_PRICE_1               1111
#define IDC_CHECK_NO_INDIVIDUAL_STOCKS  1111
#define IDC_RADIO_PRICE_2               1112
#define IDC_EDIT_TITLE                  1112
#define IDC_EDIT_MCAP_MIN               1113
#define IDC_RADIO_EPSNEXT_1             1114
#define IDC_EDIT_MCAP_MAX               1114
#define IDC_RADIO_EPSNEXT_2             1115
#define IDC_LIST_FILTER                 1115
#define IDC_EDIT_EPSNEXT                1116
#define IDC_CHECK_EXPORT_TO_EXCEL       1116
#define IDC_RADIO_EPSTHIS_1             1117
#define IDC_RADIO_GROUP_1               1117
#define IDC_RADIO_EPSTHIS_2             1118
#define IDC_RADIO_GROUP_2               1118
#define IDC_EDIT_EPSTHIS                1119
#define IDC_RADIO_GROUP_3               1119
#define IDC_RADIO_DEBT_1                1120
#define IDC_LIST_ITEMS                  1120
#define IDC_RADIO_DEBT_2                1121
#define IDC_EDIT_MIN                    1121
#define IDC_BUTTON_INCLUDE_ALL          1122
#define IDC_EDIT_MAX                    1122
#define IDC_BUTTON_EXCLUDE_ALL          1123
#define IDC_COMBO_SORT                  1123
#define IDC_CHECK_SORT_BY               1123
#define IDC_STATIC_SORT                 1124
#define IDC_EDIT_STEP                   1125
#define IDC_STATIC_NUMBER               1126
#define IDC_BUTTON_INC_ALL              1127
#define IDC_BUTTON_EXC_ALL              1128
#define IDC_BUTTON_INVERSE              1129
#define IDC_STATIC_MINMAX               1130
#define IDC_EDIT_SERVER_1               1131
#define IDC_EDIT_LOGIN_1                1132
#define IDC_RADIO_1                     1132
#define IDC_EDIT_PASSWORD_1             1133
#define IDC_RADIO_2                     1133
#define IDC_EDIT_NOTES_VALUATION        1133
#define IDC_EDIT_SERVER_2               1134
#define IDC_RADIO_3                     1134
#define IDC_EDIT_NOTES_FUNDAMENTALS     1134
#define IDC_EDIT_LOGIN_2                1135
#define IDC_RADIO_4                     1135
#define IDC_EDIT_NOTES_MANAGEMENT       1135
#define IDC_EDIT_PASSWORD_2             1136
#define IDC_RADIO_5                     1136
#define IDC_STATIC_PLACE_METRICS        1136
#define IDC_EDIT_SERVER_3               1137
#define IDC_RADIO_6                     1137
#define IDC_EDIT_ONELINER               1137
#define IDC_EDIT_LOGIN_3                1138
#define IDC_SLIDER_VALUATION            1138
#define IDC_EDIT_PASSWORD_3             1139
#define IDC_SLIDER_FUNDAMENTALS         1139
#define IDC_RADIO_1_0                   1139
#define IDC_RADIO_1_1                   1140
#define IDC_EDIT_1                      1141
#define IDC_OK                          1142
#define IDC_EDIT_11                     1142
#define IDC_COMBO1                      1143
#define IDC_EDIT_12                     1143
#define IDC_RADIO_2_0                   1144
#define IDC_RADIO_DB                    1144
#define IDC_EDIT_13                     1144
#define IDC_RADIO_2_1                   1145
#define IDC_RADIO_DB2                   1145
#define IDC_CHANGE_PASSWORD             1145
#define IDC_EDIT_14                     1145
#define IDC_EDIT_2                      1146
#define IDC_EDIT_PASSWORD_OLD           1146
#define IDC_EDIT_15                     1146
#define IDC_RADIO_3_0                   1147
#define IDC_CONFIRM                     1147
#define IDC_EDIT_16                     1147
#define IDC_RADIO_3_1                   1148
#define IDC_STATIC_CONF_WEIGHT          1148
#define IDC_EDIT_17                     1148
#define IDC_EDIT_3                      1149
#define IDC_STATIC_CONF_BIAS            1149
#define IDC_RADIO_4_0                   1150
#define IDC_RADIO_SCORE_1_2             1150
#define IDC_RADIO_4_1                   1151
#define IDC_RADIO_SCORE_1_3             1151
#define IDC_EDIT_4                      1152
#define IDC_RADIO_SCORE_2_1             1152
#define IDC_RADIO_5_0                   1153
#define IDC_RADIO_SCORE_2_2             1153
#define IDC_RADIO_5_1                   1154
#define IDC_RADIO_SCORE_2_3             1154
#define IDC_EDIT_5                      1155
#define IDC_RADIO_SCORE_3_1             1155
#define IDC_RADIO_6_0                   1156
#define IDC_RADIO_SCORE_3_2             1156
#define IDC_RADIO_6_1                   1157
#define IDC_RADIO_SCORE_3_3             1157
#define IDC_EDIT_6                      1158
#define IDC_RADIO_SCORE_4_1             1158
#define IDC_RADIO_7_0                   1159
#define IDC_RADIO_SCORE_4_2             1159
#define IDC_RADIO_7_1                   1160
#define IDC_RADIO_SCORE_4_3             1160
#define IDC_EDIT_7                      1161
#define IDC_RADIO_SCORE_5_1             1161
#define IDC_RADIO_8_0                   1162
#define IDC_RADIO_SCORE_5_2             1162
#define IDC_RADIO_8_1                   1163
#define IDC_RADIO_SCORE_5_3             1163
#define IDC_EDIT_8                      1164
#define IDC_RADIO_SCORE_6_1             1164
#define IDC_RADIO_9_0                   1165
#define IDC_RADIO_SCORE_6_2             1165
#define IDC_RADIO_9_1                   1166
#define IDC_RADIO_SCORE_6_3             1166
#define IDC_EDIT_9                      1167
#define IDC_RADIO_SCORE_7_1             1167
#define IDC_CANCEL                      1168
#define IDC_RADIO_SCORE_7_2             1168
#define IDC_EDIT_THESIS                 1169
#define IDC_RADIO27                     1169
#define IDC_RADIO_10_0                  1170
#define IDC_RADIO28                     1170
#define IDC_RADIO_10_1                  1171
#define IDC_RADIO29                     1171
#define IDC_EDIT_10                     1172
#define IDC_RADIO30                     1172
#define IDC_RADIO31                     1173
#define IDC_RADIO32                     1174
#define IDC_RADIO33                     1175
#define IDC_RADIO34                     1176
#define IDC_RADIO35                     1177
#define IDC_RADIO36                     1178
#define IDC_RADIO37                     1179
#define IDC_RADIO38                     1180
#define IDC_RADIO39                     1181
#define IDC_RADIO40                     1182
#define IDC_RADIO41                     1183
#define IDC_RADIO42                     1184
#define IDC_EDIT_18                     1194
#define IDC_EDIT_19                     1200
#define IDC_EDIT_20                     1206
#define IDC_EDIT_21                     1212
#define IDC_STATIC_SCORE_TOTAL          1214
#define IDC_STATIC_SCORE_FUND           1215
#define IDC_STATIC_SCORE_VAL            1216
#define IDC_RADIO_SCORE_1_1             1217
#define IDC_LIST_RAW                    1218
#define IDC_BUTTON1                     1219
#define IDC_BUTTON_RAW_ADD              1219
#define IDC_BUTTON2                     1220
#define IDC_BUTTON_RAW_DEL              1220
#define IDC_LIST_RAW2                   1221
#define IDC_LIST_WIP                    1221
#define IDC_BUTTON3                     1222
#define IDC_BUTTON_WIP_ADD              1222
#define IDC_BUTTON4                     1223
#define IDC_BUTTON_WIP_DEL              1223
#define IDC_LIST_RAW3                   1224
#define IDC_LIST_QC                     1224
#define IDC_BUTTON5                     1225
#define IDC_BUTTON_QC_ADD               1225
#define IDC_BUTTON6                     1226
#define IDC_BUTTON_QC_DEL               1226
#define IDC_LIST_RAW4                   1227
#define IDC_LIST_ADDWEIGHT              1227
#define IDC_BUTTON7                     1228
#define IDC_BUTTON_ADDWEIGHT_ADD        1228
#define IDC_BUTTON8                     1229
#define IDC_BUTTON_ADDWEIGHT_DEL        1229
#define IDC_LIST_RAW5                   1230
#define IDC_LIST_PORT                   1230
#define IDC_BUTTON9                     1231
#define IDC_BUTTON_PORT_ADD             1231
#define IDC_BUTTON10                    1232
#define IDC_BUTTON_PORT_DEL             1232
#define IDC_LIST_RAW6                   1233
#define IDC_LIST_SD                     1233
#define IDC_BUTTON11                    1234
#define IDC_BUTTON_SD_ADD               1234
#define IDC_BUTTON12                    1235
#define IDC_BUTTONSD_DEL                1235
#define IDC_LIST_RAW7                   1236
#define IDC_LIST_REDUCE                 1236
#define IDC_BUTTON13                    1237
#define IDC_BUTTON_REDUCE_ADD           1237
#define IDC_BUTTON14                    1238
#define IDC_BUTTON_REDUCE_DEL           1238
#define IDC_LIST_RAW8                   1239
#define IDC_LIST_TRUCK                  1239
#define IDC_BUTTON15                    1240
#define IDC_BUTTON_TRUCK_ADD            1240
#define IDC_BUTTON16                    1241
#define IDC_BUTTON_TRUCK_DEL            1241
#define IDC_BUTTON_CLOSE                1242
#define ID_GENERAL_CALC                 32772
#define ID_GENERAL_SAVE                 32773
#define ID_GENERAL_SPLIT                32774
#define ID_GENERAL_EXCEL                32775
#define ID_GENERAL_WORD                 32776
#define ID_GENERAL_GRAPH                32777
#define ID_GENERAL_OPEN                 32778
#define ID_GENERAL_SAVETODB             32779
#define ID_GENERAL_SENS_ANALYSIS        32780
#define ID_GENERAL_MONTECARLO           32781
#define ID_FILE_EXPORT_VALUES           32782
#define ID_APP_LAST_EPS_YEAR            32783
#define ID_GENERAL_LAST_EPS_YEAR        32784
#define ID_APP_MACROPARAMS              32785
#define ID_APP_UPLOAD_DATA              32787
#define ID_APP_COMPANIES                32788
#define ID_BUTTON32789                  32789
#define ID_APP_SECTORS                  32790
#define ID_APP_INDUSTRIES               32792
#define ID_APP_UPLOAD_HISTORY           32793
#define ID_GENERAL_HISTORY              32794
#define ID_GOTO                         32795
#define ID_HISTORY_GOTO                 32796
#define ID_HISTORY_DELETE               32797
#define ID_HISTORY_SAVE                 32798
#define ID_HISTORY_EXCEL                32799
#define ID_HISTORY_GRAPH                32800
#define ID_GENERAL_ADD_TO_HISTORY       32801
#define ID_BUTTON32802                  32802
#define ID_HISTORY_ADD_TO_HISTORY       32804
#define ID_APP_ADD_TO_HISTORY           32805
#define ID_APP_DELETE_HISTORY_ITEM      32806
#define ID_APP_CHARTS                   32808
#define ID_APP_UPLOAD_WEIGHTS           32809
#define ID_HISTORY_COPY                 32810
#define ID_GENERAL_DATE                 32811
#define ID_APP_PRICE_DATE               32812
#define ID_HISTORY_PASTE                32814
#define ID_APP_MEETINGS                 32816
#define ID_MEETINGS_NEW                 32817
#define ID_MEETINGS_DELETE              32818
#define ID_MEETINGS_SAVE                32819
#define ID_MEETINGS_FILTER              32820
#define ID_MEETINGS_HISTORY             32821
#define ID_MEETINGS_CHART               32823
#define ID_MEETINGS_COMPANY             32824
#define ID_CHARTS_FROM                  32825
#define ID_CHARTS_END                   32826
#define ID_GENERAL_EPS                  32827
#define ID_APP_CHECK_SPLITS             32828
#define ID_APP_CHECK_DATA               32829
#define ID_HISTORY_PRINT                32830
#define ID_CHARTS_TABLE                 32831
#define ID_VIEW_WORKBAR                 32832
#define ID_VIEW_WORKSPACE               32833
#define ID_CHANGES_OPEN                 32834
#define ID_CHANGES_COPY                 32836
#define ID_CHANGES_EXCEL                32837
#define ID_CHANGES_PRINT                32838
#define ID_TABLE_COPY                   32839
#define ID_TABLE_EXCEL                  32840
#define ID_TABLE_PRINT                  32841
#define ID_APP_REPORT_EBITDA_LEVERAGE   32842
#define ID_APP_REPORT_EARNINGS_MOMENTUM 32844
#define ID_APP_REPORT_FY_END            32846
#define ID_APP_REPORT_GENERAL           32847
#define ID_APP_MAP                      32848
#define ID_GENERAL_MEETINGS             32849
#define ID_MAP_FROM                     32850
#define ID_MAP_END                      32851
#define ID_MAP_HISTORY                  32853
#define ID_MAP_GRAPH                    32855
#define ID_MAP_STEP                     32857
#define ID_APP_REPORT_VALUE_MOMENTUM    32858
#define ID_CONNECT_SERVERS              32859
#define ID_APP_MAPSECTORS               32861
#define ID_APP_SELECT_UNIVERSE          32863
#define ID_APP_SUMMARIES                32865
#define ID_DAILYSUMS_NEW                32866
#define ID_DAILYSUMS_DELETE             32867
#define ID_DAILYSUMS_SAVE               32868
#define ID_DAILYSUMS_COMPANY            32869
#define ID_DAILYSUMS_HISTORY            32870
#define ID_DAILYSUMS_CHART              32871
#define ID_GENERAL_2MINUTE              32872
#define ID_DAILYSUMS_2MINUTE            32873
#define ID_DAILYSUMS_PRINT              32874
#define ID_DAILYSUMS_UNLOCK             32875
#define ID_DAILYSUMS_LOCK               32876
#define ID_APP_CHANGE_PASSWORD          32877
#define ID_APP_INVPROCESS               32878

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1243
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
